services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: mcpe-server
    restart: unless-stopped
    environment:
      EULA: 'TRUE'
      GAMEMODE: survival
      DIFFICULTY: hard
      ENABLE_SSH: 'TRUE'
    ports:
      - 19132:19132
    expose:
      # This is a reminder that this port is exposed to other containers in this compose file.
      - 2222
    volumes:
      - ./bds:/data

  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      # Make sure the minecraft service starts before the backup
      - 'bds'
    environment:
      # Without this, your log timestamps will be in the GMT timezone.
      TZ: 'America/Sao_Paulo'
    volumes:
      # (Optional) Map a configuration folder separately from the backups.
      # - /minecraft/backup-config:/config
      # Map your backups folder into /data
      - ./minecraft/backups:/data
      # Map your server's data folder wherever you like
      - ./bds:/bds
      - ./backup-bds/config/:/config/

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
